index:
  path: /{_locale}
  controller: App\Controller\IndexController::index
  defaults:
    _locale: es
  requirements:
    _locale: es|en
translator:
  path: /translator
  controller: App\Controller\TranslatorController::index
generator:
  path: /generator
  controller: App\Controller\GeneratorController::index
ajax:
  path: /ajax
  controller: App\Controller\AjaxController::ajax
